markdown: rdiscount
highlighter: true

name: Ravi Shankar
url: http://ravs.me
email: ravishankar.bit@gmail.com
description: Personal site of Ravi Shankar - aka RAVS
short_desc: Software Engineer , Web Enthusiast, Coffee Aficionado, Adventurer, ASU Alumni & SDE @ Amazon.
twitter: ravs24
github: ravs
flickr: ravs24
abouteme: ravs
instagram: ra_vs
linkedin: ravishankarbit
gravatar_url: http://www.gravatar.com/avatar/eeb0bc72278473bba1456b8fbabad217
heroaws_url: https://s3.amazonaws.com/ravs/hero/
resumeaws_url: http://ravs.s3-website-us-east-1.amazonaws.com/resume/RaviShankarCV.pdf
