markdown: rdiscount
pygments: true

name: Ravi Shankar
url: http://ravs.me
email: ravishankar.bit@gmail.com
description: Personal site of Ravi Shankar - aka RAVS
twitter: ravs24
github: ravs
flickr: ravs24
abouteme: ravs
gravatar_url: http://www.gravatar.com/avatar/eeb0bc72278473bba1456b8fbabad217
heroaws_url: https://s3.amazonaws.com/ravs/hero/
resumeaws_url: http://ravs.s3-website-us-east-1.amazonaws.com/resume/RaviShankarCV.pdf